### ISSUE TITLE
Pagina Sobre

### ISSUE THREAD

**Issue by marcosnoberto** [marioxaxa/ReceibaReceitas#7]
![image](https://github.com/marioxaxa/ReceibaReceitas/assets/112330160/05d37f6e-759e-481a-b3a4-391dfff3df1d)

**Comment by marioxaxa** [comment]
![image](https://github.com/marioxaxa/ReceibaReceitas/assets/66087369/71457e88-41b5-4525-bebd-28a115ef2f57)
Acho que falta por uma responsividade melhor aqui. Tenta por um keyframe para as imagens da equipe ficar acima dos textos de apresentação de cada um. Acredito que só mudar um flex direction de row pra column resolveria. :D
